# Just the Docs configuration
title: fragilesilver
description: Personal portfolio & software showcase by fragilesilver.
theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://fragilesilver.github.io
permalink: pretty


# Custom fskit theme
color_scheme: fskit

logo: "/assets/icons/fragilesilver-logo.svg"
favicon_ico: "/assets/icons/favicon.svg"

# Search settings
search_enabled: true
search:
  heading_level: 3
  tokenizer_separator: /[\s/]+/

heading_anchors: true

aux_links:
  "GitHub": "https://github.com/fragilesilver"
  "muOS.dev": "https://muos.dev"

# Navigation
nav_sort: nav_order

# Callout styling
callouts:
  note:
    title: Note
    color: purple
  tip:
    title: Tip
    color: green
  warning:
    title: Warning
    color: blue
  important:
    title: Important
    color: yellow

plugins:
  - jekyll-seo-tag
